# Generated by Django 4.0.3 on 2022-04-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
